# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GG\2015-10-05_bitbucket_api_plugin\qgisgroup\ggapi\ui\poi_dist.ui'
#
# Created: Mon Sep 12 11:29:12 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ClosestPOI_Dialog(object):
    def setupUi(self, ClosestPOI_Dialog):
        ClosestPOI_Dialog.setObjectName(_fromUtf8("ClosestPOI_Dialog"))
        ClosestPOI_Dialog.setWindowModality(QtCore.Qt.NonModal)
        ClosestPOI_Dialog.resize(392, 652)
        ClosestPOI_Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ClosestPOI_Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.POIlayerlabel = QtGui.QLabel(ClosestPOI_Dialog)
        self.POIlayerlabel.setObjectName(_fromUtf8("POIlayerlabel"))
        self.verticalLayout_3.addWidget(self.POIlayerlabel)
        self.POIlayer = QtGui.QComboBox(ClosestPOI_Dialog)
        self.POIlayer.setObjectName(_fromUtf8("POIlayer"))
        self.verticalLayout_3.addWidget(self.POIlayer)
        self.gridLayout.addLayout(self.verticalLayout_3, 4, 0, 1, 3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(ClosestPOI_Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.outFile = QtGui.QLineEdit(ClosestPOI_Dialog)
        self.outFile.setReadOnly(True)
        self.outFile.setObjectName(_fromUtf8("outFile"))
        self.horizontalLayout_2.addWidget(self.outFile)
        self.btnFile = QtGui.QPushButton(ClosestPOI_Dialog)
        self.btnFile.setObjectName(_fromUtf8("btnFile"))
        self.horizontalLayout_2.addWidget(self.btnFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.addToMap_checkBox = QtGui.QCheckBox(ClosestPOI_Dialog)
        self.addToMap_checkBox.setChecked(True)
        self.addToMap_checkBox.setObjectName(_fromUtf8("addToMap_checkBox"))
        self.verticalLayout_2.addWidget(self.addToMap_checkBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 8, 0, 1, 3)
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.inFieldlabel = QtGui.QLabel(ClosestPOI_Dialog)
        self.inFieldlabel.setObjectName(_fromUtf8("inFieldlabel"))
        self.vboxlayout.addWidget(self.inFieldlabel)
        self.inField = QtGui.QComboBox(ClosestPOI_Dialog)
        self.inField.setObjectName(_fromUtf8("inField"))
        self.vboxlayout.addWidget(self.inField)
        self.gridLayout.addLayout(self.vboxlayout, 1, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(ClosestPOI_Dialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 10, 1, 1, 2)
        self.progressBar = QtGui.QProgressBar(ClosestPOI_Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 10, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.inPointlabel = QtGui.QLabel(ClosestPOI_Dialog)
        self.inPointlabel.setObjectName(_fromUtf8("inPointlabel"))
        self.verticalLayout.addWidget(self.inPointlabel)
        self.inPoint = QtGui.QComboBox(ClosestPOI_Dialog)
        self.inPoint.setObjectName(_fromUtf8("inPoint"))
        self.verticalLayout.addWidget(self.inPoint)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.groupBox_POI_boxes = QtGui.QGroupBox(ClosestPOI_Dialog)
        self.groupBox_POI_boxes.setObjectName(_fromUtf8("groupBox_POI_boxes"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_POI_boxes)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_airport = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_airport.setObjectName(_fromUtf8("checkBox_airport"))
        self.gridLayout_2.addWidget(self.checkBox_airport, 5, 0, 1, 1)
        self.checkBox_pharmacy = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_pharmacy.setObjectName(_fromUtf8("checkBox_pharmacy"))
        self.gridLayout_2.addWidget(self.checkBox_pharmacy, 0, 0, 1, 1)
        self.checkBox_library = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_library.setObjectName(_fromUtf8("checkBox_library"))
        self.gridLayout_2.addWidget(self.checkBox_library, 1, 0, 1, 1)
        self.checkBox_junction = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_junction.setObjectName(_fromUtf8("checkBox_junction"))
        self.gridLayout_2.addWidget(self.checkBox_junction, 0, 1, 1, 1)
        self.checkBox_hospital = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_hospital.setObjectName(_fromUtf8("checkBox_hospital"))
        self.gridLayout_2.addWidget(self.checkBox_hospital, 3, 0, 1, 1)
        self.checkBox_school = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_school.setObjectName(_fromUtf8("checkBox_school"))
        self.gridLayout_2.addWidget(self.checkBox_school, 2, 1, 1, 1)
        self.checkBox_forest = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_forest.setObjectName(_fromUtf8("checkBox_forest"))
        self.gridLayout_2.addWidget(self.checkBox_forest, 3, 1, 1, 1)
        self.checkBox_doctor = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_doctor.setObjectName(_fromUtf8("checkBox_doctor"))
        self.gridLayout_2.addWidget(self.checkBox_doctor, 6, 0, 1, 1)
        self.checkBox_train = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_train.setObjectName(_fromUtf8("checkBox_train"))
        self.gridLayout_2.addWidget(self.checkBox_train, 1, 1, 1, 1)
        self.checkBox_daycare = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_daycare.setObjectName(_fromUtf8("checkBox_daycare"))
        self.gridLayout_2.addWidget(self.checkBox_daycare, 2, 0, 1, 1)
        self.checkBox_metro = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_metro.setObjectName(_fromUtf8("checkBox_metro"))
        self.gridLayout_2.addWidget(self.checkBox_metro, 7, 0, 1, 1)
        self.checkBox_stop = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_stop.setObjectName(_fromUtf8("checkBox_stop"))
        self.gridLayout_2.addWidget(self.checkBox_stop, 5, 1, 1, 1)
        self.checkBox_supermarket = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_supermarket.setObjectName(_fromUtf8("checkBox_supermarket"))
        self.gridLayout_2.addWidget(self.checkBox_supermarket, 6, 1, 1, 1)
        self.checkBox_coast = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_coast.setObjectName(_fromUtf8("checkBox_coast"))
        self.gridLayout_2.addWidget(self.checkBox_coast, 4, 0, 1, 1)
        self.checkBox_strain = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_strain.setObjectName(_fromUtf8("checkBox_strain"))
        self.gridLayout_2.addWidget(self.checkBox_strain, 4, 1, 1, 1)
        self.checkBox_lake = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_lake.setObjectName(_fromUtf8("checkBox_lake"))
        self.gridLayout_2.addWidget(self.checkBox_lake, 7, 1, 1, 1)
        self.checkBox_custom = QtGui.QCheckBox(self.groupBox_POI_boxes)
        self.checkBox_custom.setObjectName(_fromUtf8("checkBox_custom"))
        self.gridLayout_2.addWidget(self.checkBox_custom, 8, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_POI_boxes, 2, 0, 1, 3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.POIfieldlabel = QtGui.QLabel(ClosestPOI_Dialog)
        self.POIfieldlabel.setObjectName(_fromUtf8("POIfieldlabel"))
        self.verticalLayout_4.addWidget(self.POIfieldlabel)
        self.POIfield = QtGui.QComboBox(ClosestPOI_Dialog)
        self.POIfield.setObjectName(_fromUtf8("POIfield"))
        self.verticalLayout_4.addWidget(self.POIfield)
        self.gridLayout.addLayout(self.verticalLayout_4, 5, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(ClosestPOI_Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.rdoBike = QtGui.QRadioButton(self.groupBox_2)
        self.rdoBike.setEnabled(True)
        self.rdoBike.setObjectName(_fromUtf8("rdoBike"))
        self.gridlayout.addWidget(self.rdoBike, 1, 0, 1, 1)
        self.rdoCar = QtGui.QRadioButton(self.groupBox_2)
        self.rdoCar.setChecked(True)
        self.rdoCar.setObjectName(_fromUtf8("rdoCar"))
        self.gridlayout.addWidget(self.rdoCar, 0, 0, 1, 1)
        self.rdoWalk = QtGui.QRadioButton(self.groupBox_2)
        self.rdoWalk.setEnabled(True)
        self.rdoWalk.setObjectName(_fromUtf8("rdoWalk"))
        self.gridlayout.addWidget(self.rdoWalk, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 6, 0, 1, 3)

        self.retranslateUi(ClosestPOI_Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ClosestPOI_Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(ClosestPOI_Dialog)

    def retranslateUi(self, ClosestPOI_Dialog):
        ClosestPOI_Dialog.setWindowTitle(_translate("ClosestPOI_Dialog", "Distance to POI", None))
        self.POIlayerlabel.setText(_translate("ClosestPOI_Dialog", "POI input layer", None))
        self.label.setText(_translate("ClosestPOI_Dialog", "Output file", None))
        self.btnFile.setText(_translate("ClosestPOI_Dialog", "Browse", None))
        self.addToMap_checkBox.setText(_translate("ClosestPOI_Dialog", "Add to project", None))
        self.inFieldlabel.setText(_translate("ClosestPOI_Dialog", "Input unique ID field", None))
        self.inPointlabel.setText(_translate("ClosestPOI_Dialog", "Input Layer", None))
        self.groupBox_POI_boxes.setTitle(_translate("ClosestPOI_Dialog", "Distance to", None))
        self.checkBox_airport.setText(_translate("ClosestPOI_Dialog", "Airport", None))
        self.checkBox_pharmacy.setText(_translate("ClosestPOI_Dialog", "Pharmacy", None))
        self.checkBox_library.setText(_translate("ClosestPOI_Dialog", "Library", None))
        self.checkBox_junction.setText(_translate("ClosestPOI_Dialog", "Highway junction", None))
        self.checkBox_hospital.setText(_translate("ClosestPOI_Dialog", "Hospital", None))
        self.checkBox_school.setText(_translate("ClosestPOI_Dialog", "School", None))
        self.checkBox_forest.setText(_translate("ClosestPOI_Dialog", "Forest", None))
        self.checkBox_doctor.setText(_translate("ClosestPOI_Dialog", "Doctor", None))
        self.checkBox_train.setText(_translate("ClosestPOI_Dialog", "Train", None))
        self.checkBox_daycare.setText(_translate("ClosestPOI_Dialog", "Daycare", None))
        self.checkBox_metro.setText(_translate("ClosestPOI_Dialog", "Metro", None))
        self.checkBox_stop.setText(_translate("ClosestPOI_Dialog", "Bus stop", None))
        self.checkBox_supermarket.setText(_translate("ClosestPOI_Dialog", "Supermarket", None))
        self.checkBox_coast.setText(_translate("ClosestPOI_Dialog", "Coast", None))
        self.checkBox_strain.setText(_translate("ClosestPOI_Dialog", "S-Train", None))
        self.checkBox_lake.setText(_translate("ClosestPOI_Dialog", "Lake", None))
        self.checkBox_custom.setText(_translate("ClosestPOI_Dialog", "Custom layer", None))
        self.POIfieldlabel.setText(_translate("ClosestPOI_Dialog", "POI layer unique ID field", None))
        self.groupBox_2.setTitle(_translate("ClosestPOI_Dialog", "Transportmiddel", None))
        self.rdoBike.setText(_translate("ClosestPOI_Dialog", "Bicycle", None))
        self.rdoCar.setText(_translate("ClosestPOI_Dialog", "Car", None))
        self.rdoWalk.setText(_translate("ClosestPOI_Dialog", "Walk", None))

