# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GG\2015-10-05_bitbucket_api_plugin\qgisgroup\ggapi\ui\servicearea.ui'
#
# Created: Mon Sep 12 11:29:12 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Servicearea_Dialog(object):
    def setupUi(self, Servicearea_Dialog):
        Servicearea_Dialog.setObjectName(_fromUtf8("Servicearea_Dialog"))
        Servicearea_Dialog.setWindowModality(QtCore.Qt.NonModal)
        Servicearea_Dialog.resize(444, 607)
        Servicearea_Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(Servicearea_Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(Servicearea_Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.rdoWalk = QtGui.QRadioButton(self.groupBox_2)
        self.rdoWalk.setEnabled(True)
        self.rdoWalk.setObjectName(_fromUtf8("rdoWalk"))
        self.mot = QtGui.QButtonGroup(Servicearea_Dialog)
        self.mot.setObjectName(_fromUtf8("mot"))
        self.mot.addButton(self.rdoWalk)
        self.gridlayout.addWidget(self.rdoWalk, 3, 0, 1, 1)
        self.rdoBike = QtGui.QRadioButton(self.groupBox_2)
        self.rdoBike.setEnabled(True)
        self.rdoBike.setObjectName(_fromUtf8("rdoBike"))
        self.mot.addButton(self.rdoBike)
        self.gridlayout.addWidget(self.rdoBike, 2, 0, 1, 1)
        self.rdoCar = QtGui.QRadioButton(self.groupBox_2)
        self.rdoCar.setChecked(True)
        self.rdoCar.setObjectName(_fromUtf8("rdoCar"))
        self.mot.addButton(self.rdoCar)
        self.gridlayout.addWidget(self.rdoCar, 1, 0, 1, 1)
        self.walk_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.walk_lineEdit.setEnabled(False)
        self.walk_lineEdit.setText(_fromUtf8(""))
        self.walk_lineEdit.setObjectName(_fromUtf8("walk_lineEdit"))
        self.gridlayout.addWidget(self.walk_lineEdit, 3, 2, 1, 1)
        self.rdoPublic = QtGui.QRadioButton(self.groupBox_2)
        self.rdoPublic.setChecked(False)
        self.rdoPublic.setObjectName(_fromUtf8("rdoPublic"))
        self.mot.addButton(self.rdoPublic)
        self.gridlayout.addWidget(self.rdoPublic, 4, 0, 1, 1)
        self.bike_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.bike_lineEdit.setEnabled(False)
        self.bike_lineEdit.setText(_fromUtf8(""))
        self.bike_lineEdit.setObjectName(_fromUtf8("bike_lineEdit"))
        self.gridlayout.addWidget(self.bike_lineEdit, 2, 2, 1, 1)
        self.date_comboBox = QtGui.QComboBox(self.groupBox_2)
        self.date_comboBox.setEnabled(False)
        self.date_comboBox.setObjectName(_fromUtf8("date_comboBox"))
        self.date_comboBox.addItem(_fromUtf8(""))
        self.date_comboBox.addItem(_fromUtf8(""))
        self.date_comboBox.addItem(_fromUtf8(""))
        self.date_comboBox.addItem(_fromUtf8(""))
        self.date_comboBox.addItem(_fromUtf8(""))
        self.date_comboBox.addItem(_fromUtf8(""))
        self.date_comboBox.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.date_comboBox, 4, 1, 1, 1)
        self.timeEdit = QtGui.QTimeEdit(self.groupBox_2)
        self.timeEdit.setEnabled(False)
        self.timeEdit.setTime(QtCore.QTime(8, 0, 0))
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.gridlayout.addWidget(self.timeEdit, 4, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 3)
        self.groupBox = QtGui.QGroupBox(Servicearea_Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineEdit_times = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_times.setAutoFillBackground(False)
        self.lineEdit_times.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_times.setObjectName(_fromUtf8("lineEdit_times"))
        self.verticalLayout_3.addWidget(self.lineEdit_times)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(Servicearea_Dialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 7, 1, 1, 2)
        self.progressBar = QtGui.QProgressBar(Servicearea_Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 7, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.inPointlabel = QtGui.QLabel(Servicearea_Dialog)
        self.inPointlabel.setObjectName(_fromUtf8("inPointlabel"))
        self.verticalLayout.addWidget(self.inPointlabel)
        self.inPoint = QtGui.QComboBox(Servicearea_Dialog)
        self.inPoint.setObjectName(_fromUtf8("inPoint"))
        self.verticalLayout.addWidget(self.inPoint)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(Servicearea_Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.outFile = QtGui.QLineEdit(Servicearea_Dialog)
        self.outFile.setReadOnly(True)
        self.outFile.setObjectName(_fromUtf8("outFile"))
        self.horizontalLayout_2.addWidget(self.outFile)
        self.btnFile = QtGui.QPushButton(Servicearea_Dialog)
        self.btnFile.setObjectName(_fromUtf8("btnFile"))
        self.horizontalLayout_2.addWidget(self.btnFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.addToMap_checkBox = QtGui.QCheckBox(Servicearea_Dialog)
        self.addToMap_checkBox.setChecked(True)
        self.addToMap_checkBox.setObjectName(_fromUtf8("addToMap_checkBox"))
        self.verticalLayout_2.addWidget(self.addToMap_checkBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 5, 0, 1, 3)
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.inFieldlabel = QtGui.QLabel(Servicearea_Dialog)
        self.inFieldlabel.setObjectName(_fromUtf8("inFieldlabel"))
        self.vboxlayout.addWidget(self.inFieldlabel)
        self.inField = QtGui.QComboBox(Servicearea_Dialog)
        self.inField.setObjectName(_fromUtf8("inField"))
        self.vboxlayout.addWidget(self.inField)
        self.gridLayout.addLayout(self.vboxlayout, 1, 0, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(Servicearea_Dialog)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.bufferEdit = QtGui.QLineEdit(self.groupBox_3)
        self.bufferEdit.setEnabled(True)
        self.bufferEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.bufferEdit.setObjectName(_fromUtf8("bufferEdit"))
        self.horizontalLayout.addWidget(self.bufferEdit)
        self.gridLayout.addWidget(self.groupBox_3, 4, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)

        self.retranslateUi(Servicearea_Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Servicearea_Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Servicearea_Dialog)

    def retranslateUi(self, Servicearea_Dialog):
        Servicearea_Dialog.setWindowTitle(_translate("Servicearea_Dialog", "Service area", None))
        self.groupBox_2.setTitle(_translate("Servicearea_Dialog", "Mode of transport", None))
        self.rdoWalk.setText(_translate("Servicearea_Dialog", "Walk", None))
        self.rdoBike.setText(_translate("Servicearea_Dialog", "Bicycle", None))
        self.rdoCar.setText(_translate("Servicearea_Dialog", "Car", None))
        self.rdoPublic.setText(_translate("Servicearea_Dialog", "Public transport", None))
        self.bike_lineEdit.setToolTip(_translate("Servicearea_Dialog", "Bicycle speed", None))
        self.date_comboBox.setItemText(0, _translate("Servicearea_Dialog", "Monday", None))
        self.date_comboBox.setItemText(1, _translate("Servicearea_Dialog", "Tuesday", None))
        self.date_comboBox.setItemText(2, _translate("Servicearea_Dialog", "Wednesday", None))
        self.date_comboBox.setItemText(3, _translate("Servicearea_Dialog", "Thursday", None))
        self.date_comboBox.setItemText(4, _translate("Servicearea_Dialog", "Friday", None))
        self.date_comboBox.setItemText(5, _translate("Servicearea_Dialog", "Saturday", None))
        self.date_comboBox.setItemText(6, _translate("Servicearea_Dialog", "Sunday", None))
        self.timeEdit.setDisplayFormat(_translate("Servicearea_Dialog", "HH:mm", None))
        self.groupBox.setTitle(_translate("Servicearea_Dialog", "Times in minutes", None))
        self.label_2.setText(_translate("Servicearea_Dialog", "E.g. 5;15;30", None))
        self.inPointlabel.setText(_translate("Servicearea_Dialog", "Input layer", None))
        self.label.setText(_translate("Servicearea_Dialog", "Output file", None))
        self.btnFile.setText(_translate("Servicearea_Dialog", "Browse", None))
        self.addToMap_checkBox.setText(_translate("Servicearea_Dialog", "Add to map", None))
        self.inFieldlabel.setText(_translate("Servicearea_Dialog", "Input unique ID field", None))
        self.groupBox_3.setTitle(_translate("Servicearea_Dialog", "Buffer on roads", None))
        self.bufferEdit.setText(_translate("Servicearea_Dialog", "0", None))

